SECP_project/urls.py
from django.contrib import admin
import debug_toolbar
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.conf.urls import url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.static import serve as mediaserve


urlpatterns = [
    path('admin/', admin.site.urls),
    path('myprofile/', include('myprofile.urls', namespace='myprofile')),
    path('album/', include('my_album.urls', namespace='my_album')),
    path('', include('blog.urls', namespace='blog')),
    path('summernote/', include('django_summernote.urls')),
    path('__debug__/', include(debug_toolbar.urls)),

]


urlpatterns.append(url(f'^{settings.MEDIA_URL.lstrip("/")}(?P<path>.*)$',
                       mediaserve, {'document_root': settings.MEDIA_ROOT}))



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)


urlpatterns.append(url(f'^{settings.MEDIA_URL.lstrip("/")}(?P<path>.*)$',
        mediaserve,
        {'document_root': settings.MEDIA_ROOT}))

urlpatterns += staticfiles_urlpatterns()

blog/urls.py
from functools import partial
from django.urls import path, include
from .import views

app_name = 'blog'

urlpatterns = [
     path('', views.blog_list, name = 'blog_list'),
     path('<slug:category_slug>', views.blog_category, name='blog_by_category'),
     path('blog/<slug>/', views.blog_details, name = 'blog_details'),
     path('search/', views.search_blog, name = 'search_blog'),

]

my_album/urls.py
from functools import partial
from django.urls import path, include
from .import views

app_name = 'my_album'

urlpatterns = [
     path('', views.albumspage, name = 'albumspage'),
     path('blueberry/', views.blueberry, name = 'blueberry'),
]

myprofile/urls.py
from functools import partial
from django.urls import path, include
from .import views

app_name = 'myprofile'

urlpatterns = [
     path('', views.homepage, name = 'homepage'),
]

blog/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import override
from taggit.managers import TaggableManager


# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=170)
    slug = models.SlugField(max_length=170, unique=True)
    

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:blog_by_category', args={self.slug})


class Blog(models.Model):
    category = models.ForeignKey(Category, blank=True, null=True, on_delete=models.CASCADE, related_name='blogs')
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    thumbnail = models.ImageField(upload_to = 'blog/images/')
    short_discription = models.TextField()
    discription = models.TextField()
    tags = TaggableManager()
    creation = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:blog_details', kwargs={'slug': self.slug})

    @property
    def comment_count(self):
        return Comment.objects.filter(blog=self).count()



class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=90)
    body = models.TextField()
    creation = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

my_album/models.py
from django.db import models

# Create your models here.

class Albums(models.Model):
    thumbnail = models.ImageField(upload_to = 'album/images/')
    discription = models.TextField()
    creation = models.DateTimeField(auto_now_add=True)

myprofile/models.py
from django.db import models

# Create your models here.
class Profile(models.Model):
    name = models.CharField(max_length=50)
    age = models.IntegerField()
    address = models.TextField()
    image = models.ImageField()

blog/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('name', 'body')

blog/views.py
from django.core import paginator
from django.shortcuts import render, get_object_or_404
from .forms import CommentForm
from django.http import HttpResponseRedirect
from .models import Blog, Category
from django.db.models import Q, query
from django.core.paginator import Paginator
from django.contrib import messages
from django.shortcuts import redirect

#Create your views here.

def blog_list(request):

    categories = Category.objects.all()
    blog = Blog.objects.all()
    latest_blog = Blog.objects.all()[:3]
    
    paginator = Paginator(blog, 2)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    

    context = {
        'blog':blog,
        'latest_blog':latest_blog,
        'categories':categories,
        'page_obj':page_obj
    }
    return render(request, 'blog/blog.html', context)


def blog_details(request, slug):
    categories = Category.objects.all()
    latest_blog = Blog.objects.all()[:3]
    blog = Blog.objects.get(slug=slug)
           #gattit
    similar_blogs = blog.tags.similar_objects()[:2]
    comments = blog.comments.all()

    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit = False)
            new_comment.blog=blog
            new_comment.save()

            messages.success(request, 'comment submitted')
            return HttpResponseRedirect(request.path_info)

            
    else:
        comment_form = CommentForm()


    context = {
        'blog':blog,
        'latest_blog':latest_blog,
        'categories':categories,
        #gattit
        'similar_blogs':similar_blogs,
        'comments':comments

    }
    return render(request, 'blog/details.html', context)


def search_blog(request):
    categories = Category.objects.all()
    latest_blog = Blog.objects.all()[:3]

    queryset = Blog.objects.all()
    query = request.GET.get('q')

    paginator = Paginator(queryset, 1)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    if query:
        queryset=queryset.filter(
            Q(title__icontains = query) | Q(short_discription__icontains = query) | Q(discription__icontains = query)
        ).distinct()
    
    context = {
        'queryset': queryset,
        'latest_blog':latest_blog,
        'categories':categories,
        'query': query
    }

    return render(request, 'blog/search.html', context)


def blog_category(request, category_slug= None):
    category = None
    categories = Category.objects.all()
    blog = Blog.objects.all()
    latest_blog = Blog.objects.all()[:3]
    
    paginator = Paginator(blog, 4)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        blog = blog.filter(category=category)

        paginator = Paginator(blog, 4)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)

    context = {
        'blogs':blog,
        'category':category,
        'latest_blog':latest_blog,
        'categories':categories,
        'page_obj':page_obj
    }
    return render(request, 'blog/blog_category.html', context)

my_album/views.py
from django.shortcuts import render
from .models import Albums
# Create your views here.

def albumspage(request):
    albums = Albums.objects.all()
    context = {
        'albums':albums

    }
    return render(request, 'album/albums.html', context)


def blueberry(request):

    context = {
        
    }
    return render(request, 'album/blueberry.html', context)

myprofile/views.py
from django.shortcuts import render
from .models import Profile
# Create your views here.

def homepage(request):
    profile = Profile.objects.all()
    context = {
        'profile':profile

    }
    return render(request, 'profile.html', context)

templates/album/albums.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.83.1">
    <title>My Albums</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/album/">

    

    <!-- Bootstrap core CSS -->
<link href="{% static 'assets/dist/css/bootstrap.min.css' %}" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
  </head>
  <body>
    
<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">About</h4>
          <p class="text-muted">Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Contact</h4>
          <ul class="list-unstyled">
            <li><a href="#" class="text-white">Follow on Twitter</a></li>
            <li><a href="#" class="text-white">Like on Facebook</a></li>
            <li><a href="#" class="text-white">Email me</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container">
      <a href="#" class="navbar-brand d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2" viewBox="0 0 24 24"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
        <strong>Album</strong>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>

<main>

  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Album example</h1>
        <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don’t simply skip over it entirely.</p>
        <p>
          <a href="#" class="btn btn-primary my-2">Main call to action</a>
          <a href="#" class="btn btn-secondary my-2">Secondary action</a>
        </p>
      </div>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">

        {% for album in albums %}
        <div class="col">
          <div class="card shadow-sm">
            <img class="bd-placeholder-img card-img-top" width="100%" height="225" src="{{ album.thumbnail.url }}" alt="image">

            <div class="card-body">
              <p class="card-text">{{ album.discription }}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                </div>
                <small class="text-muted">{{ album.creation | timesince }}</small>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}

      </div>
    </div>
  </div>

</main>

<footer class="text-muted py-5">
  <div class="container">
    <p class="float-end mb-1">
      <a href="#">Back to top</a>
    </p>
    <p class="mb-1">Thanks to be here!!</p>
  </div>
</footer>


    <script src="{% static 'assets/dist/js/bootstrap.bundle.min.js' %}"></script>

      
  </body>
</html>

templates/blog/blog.html
{% extends 'head.html' %}
{% load static %}
{% block title_block %} Rakib's Blog Home {% endblock %}
{% block main_block %}
    <!-- section main content -->
	<section class="main-content mt-5">
		<div class="container-xl">

			<div class="row gy-4">

				<div class="col-lg-8">

                    <div class="row gy-4">
						{% for blog in page_obj %}
                        <div class="col-sm-6">
                            <!-- post -->
                            <div class="post post-grid rounded bordered">
                                <div class="thumb top-rounded">
                                    <a href="{{ category.get_absolute_url }}" class="category-badge position-absolute">{{ blog.category.name }}</a>
                                    <span class="post-format">
                                        <i class="icon-picture"></i>
                                    </span>
                                    <a href="{{ blog.get_absolute_url }}">
                                        <div class="inner">
                                            <img src="{{ blog.thumbnail.url }}" alt="post-title" />
                                        </div>
                                    </a>
                                </div>
                                <div class="details">
                                    <ul class="meta list-inline mb-0">
                                        <li class="list-inline-item">{{ blog.creation | timesince }}</li>
                                    </ul>
                                    <h5 class="post-title mb-3 mt-3"><a href="{{ blog.get_absolute_url }}">{{ blog.title }}</a></h5>
                                    <p class="excerpt mb-0">{{ blog.short_discription }}</p>
                                </div>
                                <div class="post-bottom clearfix d-flex align-items-center">
                                    <div class="social-share me-auto">
                                        <button class="toggle-button icon-share"></button>
                                        <ul class="icons list-unstyled list-inline mb-0">
                                            <li class="list-inline-item"><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                                            <li class="list-inline-item"><a href="#"><i class="fab fa-twitter"></i></a></li>
                                            <li class="list-inline-item"><a href="#"><i class="fab fa-linkedin-in"></i></a></li>
                                        </ul>
                                    </div>
                                    <div class="more-button float-end">
                                        <a href=""><span class="icon-options"></span></a>
                                    </div>
                                </div>
                            </div>
                        </div>
						{% endfor %}
                    </div>

					<!-- pagination -->
					<nav>
						<ul class="pagination justify-content-center">


							{% load l10n %}           
							{% for blog in page_obj.paginator.page_range %}
							{% if page_obj.number == blog  %}
							<li class="page-item active" aria-current="page">
								<a href="?page={{ blog }}"><span class="page-link">{{ blog.localize }}</span></a>
							</li>
							{% else %}
							<li class="page-item"><a class="page-link" href="?page={{ blog }}">{{ blog }}</a></li>

							{% endif %}
							{% endfor %}

						</ul>
					</nav>

				</div>
				<div class="col-lg-4">

					<!-- sidebar -->
					<div class="sidebar">
						<!-- widget about -->
						<div class="widget rounded">
							<div class="widget-about data-bg-image text-center" data-bg-image="{% static 'blog/images/map-bg.png' %}">
								<img src="{% static 'blog/images/logo.svg' %}" alt="logo" class="mb-4" />
								<p class="mb-4">Hello, We’re content writer who is fascinated by content fashion, celebrity and lifestyle. We helps clients bring the right content to the right people.</p>
								<ul class="social-icons list-unstyled list-inline mb-0">
									<li class="list-inline-item"><a href="#"><i class="fab fa-facebook-f"></i></a></li>
									<li class="list-inline-item"><a href="#"><i class="fab fa-twitter"></i></a></li>
									<li class="list-inline-item"><a href="#"><i class="fab fa-instagram"></i></a></li>
									<li class="list-inline-item"><a href="#"><i class="fab fa-pinterest"></i></a></li>
									<li class="list-inline-item"><a href="#"><i class="fab fa-medium"></i></a></li>
									<li class="list-inline-item"><a href="#"><i class="fab fa-youtube"></i></a></li>
								</ul>
							</div>
						</div>

						

						<!-- widget categories -->
						<div class="widget rounded">
							<div class="widget-header text-center">
								<h3 class="widget-title">Blog Categories</h3>
								<img src="{% static 'blog/images/wave.svg' %}" class="wave" alt="wave" />
							</div>
							<div class="widget-content">
								<ul class="list">
									
									{% for category in categories %}
	
									<li><a href="{{ category.get_absolute_url }}">{{ category.name}}</a></li>
									{% endfor %}
								</ul>
							</div>
							
						</div>


						<!-- widget popular posts -->
						<div class="widget rounded">
							<div class="widget-header text-center">
								<h3 class="widget-title">Recent Posts</h3>
								<img src="{% static 'blog/images/wave.svg' %}" class="wave" alt="wave" />
							</div>

							
							{% for blog in latest_blog %}
							<div class="widget-content">
								<!-- post -->
								<div class="post post-list-sm circle">
									<div class="thumb circle">
										<span class="number">1</span>
										<a href="blog-single.html">
											<div class="inner">
												<img src="{{ blog.thumbnail.url }}" alt="post-title" />
											</div>
										</a>
									</div>
									<div class="details clearfix">
										<h6 class="post-title my-0"><a href="{{ blog.get_absolute_url }}">{{ blog.title }}</a></h6>
										<ul class="meta list-inline mt-1 mb-0">
											<li class="list-inline-item">{{ blog.creation | date}}</li>
										</ul>
									</div>
								</div>
							</div>
							{% endfor %}		
						</div>


					</div>

				</div>

			</div>

		</div>
	</section>
{% endblock %}

templates/head.html
{% load static %}
<!DOCTYPE html>
<html lang="en-US">

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title>{% block title_block %} Rakib's Blog {% endblock %}</title>
	<meta name="description" content="Katen - Minimal Blog & Magazine HTML Theme">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<link rel="shortcut icon" type="image/x-icon" href="{% static 'blog/images/favicon.png' %}">

	<!-- STYLES -->
	<link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}" type="text/css" media="all">
	<link rel="stylesheet" href="{% static 'blog/css/all.min.css' %}" type="text/css" media="all">
	<link rel="stylesheet" href="{% static 'blog/css/slick.css' %}" type="text/css" media="all">
	<link rel="stylesheet" href="{% static 'blog/css/simple-line-icons.css' %}" type="text/css" media="all">
	<link rel="stylesheet" href="{% static 'blog/css/style.css' %}" type="text/css" media="all">

	<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

<!-- preloader -->
<div id="preloader">
	<div class="book">
		<div class="inner">
			<div class="left"></div>
			<div class="middle"></div>
			<div class="right"></div>
		</div>
		<ul>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
		</ul>
	</div>
</div>

<!-- site wrapper -->
<div class="site-wrapper">

	<div class="main-overlay"></div>

	<!-- header -->
	<header class="header-personal light">
        <div class="container-xl header-top">
			<div class="row align-items-center">

				<div class="col-4 d-none d-md-block d-lg-block">
					<!-- social icons -->
					<ul class="social-icons list-unstyled list-inline mb-0">
						<li class="list-inline-item"><a href="#"><i class="fab fa-facebook-f"></i></a></li>
						<li class="list-inline-item"><a href="#"><i class="fab fa-twitter"></i></a></li>
						<li class="list-inline-item"><a href="#"><i class="fab fa-instagram"></i></a></li>
						
					</ul>
				</div>

				<div class="col-md-4 col-sm-12 col-xs-12 text-center">
				<!-- site logo -->
			
					<a class="navbar-brand" href=""><img class="rounded-circle" style="width: 85px;" src="{% static 'blog/images/other/avater.jpg' %}" alt="logo" /></a>
					<a href="" class="d-block text-logo">RAKIB DIGONTO<span class="dot">.</span></a>
					<span class="slogan d-block">Professional Writer & Personal Blogger</span>
				</div>

				<div class="col-md-4 col-sm-12 col-xs-12">
					<!-- header buttons -->
					<div class="header-buttons float-md-end mt-4 mt-md-0">
						<button class="search icon-button">
							<i class="icon-magnifier"></i>
						</button>
						<button class="burger-menu icon-button ms-2 float-end float-md-none">
							<span class="burger-icon"></span>
						</button>
					</div>
				</div>

			</div>
        </div>

		<nav class="navbar navbar-expand-lg">
			<div class="container-xl">
				
				<div class="collapse navbar-collapse justify-content-center centered-nav">
					<!-- menus -->
					<ul class="navbar-nav">
						<li class="navbar-nav-last-item active">
							<a class="nav-link" href="/">Home</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="">About</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="">Contact</a>
						</li>
					</ul>
				</div>

			</div>
		</nav>
	</header>

    <!-- section hero -->
    <section class="hero data-bg-image d-flex align-items-center" data-bg-image="{% static 'blog/images/other/hero.jpg' %}">
        <div class="container-xl">
            <!-- call to action -->
            <div class="cta text-center">
                <h2 class="mt-0 mb-4">I'm Rakib Digonto.</h2>
                <p class="mt-0 mb-4">Hello, I’m a content writer who is fascinated by content fashion, celebrity and lifestyle. She helps clients bring the right content to the right people.</p>
                <a href="#" class="btn btn-light mt-2">About Me</a>
            </div>
        </div>
        <!-- animated mouse wheel -->
        <span class="mouse">
            <span class="wheel"></span>
        </span>
        <!-- wave svg -->
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 260"><path fill="#FFF" fill-opacity="1" d="M0,256L60,245.3C120,235,240,213,360,218.7C480,224,600,256,720,245.3C840,235,960,181,1080,176C1200,171,1320,213,1380,234.7L1440,256L1440,320L1380,320C1320,320,1200,320,1080,320C960,320,840,320,720,320C600,320,480,320,360,320C240,320,120,320,60,320L0,320Z"></path></svg>
    </section>

	<!-- section main content -->
	{% block main_block %}
    
    {% endblock %}


	<!-- section main content end -->


	<!-- footer -->
    {% block body_block %}
    
    {% endblock %}
	<footer>
		<div class="container-xl">
			<div class="footer-inner">
				<div class="row d-flex align-items-center gy-4">
					<!-- copyright text -->
					<div class="col-md-4">
						<span class="copyright">©rakib digonto blog site.</span>
					</div>

					<!-- social icons -->
					<div class="col-md-4 text-center">
						<ul class="social-icons list-unstyled list-inline mb-0">
							<li class="list-inline-item"><a href="#"><i class="fab fa-facebook-f"></i></a></li>
							<li class="list-inline-item"><a href="#"><i class="fab fa-twitter"></i></a></li>
							<li class="list-inline-item"><a href="#"><i class="fab fa-instagram"></i></a></li>
							<li class="list-inline-item"><a href="#"><i class="fab fa-pinterest"></i></a></li>
							<li class="list-inline-item"><a href="#"><i class="fab fa-medium"></i></a></li>
							<li class="list-inline-item"><a href="#"><i class="fab fa-youtube"></i></a></li>
						</ul>
					</div>

					<!-- go to top button -->
					<div class="col-md-4">
						<a href="#" id="return-to-top" class="float-md-end"><i class="icon-arrow-up"></i>Back to Top</a>
					</div>
				</div>
			</div>
		</div>
	</footer>

</div>
<!-- end site wrapper -->

<!-- search popup area -->
<div class="search-popup">
	<!-- close button -->
	<button type="button" class="btn-close" aria-label="Close"></button>
	<!-- content -->
	<div class="search-content">
		<div class="text-center">
			<h3 class="mb-4 mt-0">Press ESC to close</h3>
		</div>
		
    
    <!-- form -->
		<form action="{% url 'blog:search_blog' %}" class="d-flex search-form">
      		<input class="form-control me-2" type="search" name="q" placeholder="Search what you need ..." aria-label="Search">
      		<button class="btn btn-default btn-lg" type="submit"><i class="icon-magnifier"></i></button>
		</form>

  </div>
</div>

<!-- canvas menu -->
<div class="canvas-menu d-flex align-items-end flex-column">
	<!-- close button -->
	<button type="button" class="btn-close" aria-label="Close"></button>

	<!-- logo -->
	<div class="logo">
		<a class="navbar-brand" href=""><img class="rounded-circle" style="width: 50; height: 50;" src="{% static 'blog/images/other/avater.jpg' %}" alt="logo" /></a>

		<a href="" class="d-block text-logo">RAKIB DIGONTO<span class="dot">.</span></a>
	</div>

	<!-- menu -->
	<nav>
		<ul class="vertical-menu">
			<li class="active"><a href="/">Home</a></li>
			<li><a href="">About</a></li>
			<li><a href="">Contact</a></li>
		</ul>
	</nav>

	<!-- social icons -->
	<ul class="social-icons list-unstyled list-inline mb-0 mt-auto w-100">
		<li class="list-inline-item"><a href="#"><i class="fab fa-facebook-f"></i></a></li>
		<li class="list-inline-item"><a href="#"><i class="fab fa-twitter"></i></a></li>
		<li class="list-inline-item"><a href="#"><i class="fab fa-instagram"></i></a></li>
		<li class="list-inline-item"><a href="#"><i class="fab fa-pinterest"></i></a></li>
		<li class="list-inline-item"><a href="#"><i class="fab fa-medium"></i></a></li>
		<li class="list-inline-item"><a href="#"><i class="fab fa-youtube"></i></a></li>
	</ul>
</div>

<!-- JAVA SCRIPTS -->
<script src="{% static 'blog/js/jquery.min.js' %}"></script>
<script src="{% static 'blog/js/popper.min.js' %}"></script>
<script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
<script src="{% static 'blog/js/slick.min.js' %}"></script>
<script src="{% static 'blog/js/jquery.sticky-sidebar.min.js' %}"></script>
<script src="{% static 'blog/js/custom.js' %}"></script>

</body>
</html>

templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
<h2>Homepage</h2>
{% for person in profile %}
<h3>{{ person.name }}</h3>
<img src="{{ person.image.url }}" alt="image">
<h5>{{ person.address }}</h5>
<h5>{{ person.age }}</h5>
<hr>
{% endfor %}
</body>
</html>